#!/usr/bin/env python3
"""
The TALATA:HEAD block on every page (Website v3, 2 Oct 2026).

It owns the theme-color meta and, on pages in LIGHT_OK, light mode:

  * an inline pre-paint script (a port of the dash's public/theme.js) that sets
    html.light or html.dark before the first frame, so the page never flashes.
    The visitor's footer choice wins; on Auto it follows the phone.
  * assets/talata-light.css, placed straight after talata-dark.css (or after
    talata-tw-dark.css where a page has it), so the light tokens have the last
    word.
  * assets/talata-theme.js, which draws "Theme: Auto / Light / Dark" in the
    footer.

A page joins LIGHT_OK only after it measures clean in light:
    tools/contrast-runner.html?theme=light&pages=<list>  ->  0 failures.
A page outside LIGHT_OK stays dark, which is right, rather than light and
unreadable. It also gets no theme control, so nobody can pick a light that
the page does not have.

The nav bar and footer stay navy and black in both themes, so the theme-color
is the nav navy in both.

    python3 tools/apply-head.py           rewrite pages
    python3 tools/apply-head.py --check   exit 1 if any page would change
"""
import glob
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKIP_DIRS = ("tools/", "node_modules/", "dist/", ".git/", ".wrangler/", "posters/")
SKIP = {"index-new.html", "home-classic.html", "hero-carousel-preview.html"}

# Batches roll in per the v3 plan. Add a page here only after the contrast
# runner shows it clean in light.
LIGHT_OK = {
    # batch 1
    "index.html", "join.html", "academy.html", "mini.html", "sparks.html",
    "men.html", "camps.html", "games.html", "saturday.html",
    # batch 2
    "camps/academy-u12-camp-2026.html", "camps/academy-u15-camp-2026.html",
    "camps/canada-camp-2026.html", "camps/college-pathway-camp-2026.html",
    "camps/dk-mini-summer-camp-2026.html", "camps/dk-summer-camp-2026.html",
    "camps/nida-camp-2026.html",  # spring-camp-2026 is a redirect stub, never paints
    "camps/spring-camp-u13-u15-2026.html", "camps/spring-camp-u9-u11-2026.html",
    "help.html", "help/age-groups.html", "help/first-session.html", "help/holdsport.html",
    # batch 3
    "blog.html",
}
# Every post shares one template, so a new post joins light mode on its own.
# Run the contrast runner over blog/ when that template changes.
LIGHT_PREFIXES = ("blog/",)


def light_ok(rel):
    return rel in LIGHT_OK or rel.startswith(LIGHT_PREFIXES)

START = "<!-- TALATA:HEAD:START — generated by tools/apply-head.py, do not hand-edit -->"
END = "<!-- TALATA:HEAD:END -->"
BLOCK_RE = re.compile(r"[ \t]*<!-- TALATA:HEAD:START.*?<!-- TALATA:HEAD:END -->\n?", re.S)
META_RE = re.compile(r'[ \t]*<meta name="theme-color"[^>]*>\n?', re.I)
LIGHT_LINK_RE = re.compile(r'[ \t]*<link rel="stylesheet" href="/assets/talata-light\.css[^"]*">\n?')
STAMP_RE = re.compile(r"/assets/talata-[a-z-]+\.(?:js|css)\?v=([0-9a-z]+)")

THEME_COLOR = '<meta name="theme-color" content="#0B1F3A">'

# Port of the dash's public/theme.js. Kept tiny and inline: an external file
# would be a render-blocking request, and deferring it brings the flash back.
PREPAINT = (
    "<script>(function(){var m='auto';try{var s=localStorage.getItem('talata-theme');"
    "if(s==='light'||s==='dark')m=s}catch(e){}var d=m==='dark';if(m==='auto'){try{"
    "d=matchMedia('(prefers-color-scheme: dark)').matches}catch(e){d=true}}"
    "var r=document.documentElement;r.classList.remove('light','dark');"
    "r.classList.add(d?'dark':'light');r.style.colorScheme=d?'dark':'light'})();</script>"
)


def pages():
    for p in sorted(glob.glob(os.path.join(ROOT, "**/*.html"), recursive=True)):
        rel = os.path.relpath(p, ROOT)
        if rel.startswith(SKIP_DIRS) or rel in SKIP:
            continue
        yield p, rel


def block(rel, stamp):
    lines = [START, THEME_COLOR]
    if light_ok(rel):
        lines.append(PREPAINT)
        lines.append('<script src="/assets/talata-theme.js?v=%s" defer></script>' % stamp)
    lines.append(END)
    return "\n".join(lines) + "\n"


def fix(src, rel):
    if "<head" not in src.lower():
        return src
    m = STAMP_RE.search(src)
    stamp = m.group(1) if m else "20261002a"
    s = BLOCK_RE.sub("", src)
    s = META_RE.sub("", s)
    s = LIGHT_LINK_RE.sub("", s)

    anchor = re.search(r'<meta name="viewport"[^>]*>\n?', s) or re.search(r"<meta charset[^>]*>\n?", s, re.I)
    if anchor is None:
        anchor = re.search(r"<head[^>]*>\n?", s, re.I)
    s = s[: anchor.end()] + block(rel, stamp) + s[anchor.end():]

    if light_ok(rel):
        last = None
        for last in re.finditer(r'<link rel="stylesheet" href="/assets/talata-(?:tw-)?dark\.css[^"]*">\n?', s):
            pass
        tag = '<link rel="stylesheet" href="/assets/talata-light.css?v=%s">\n' % stamp
        if last is not None:
            nl = "" if last.group(0).endswith("\n") else "\n"
            s = s[: last.end()] + nl + tag + s[last.end():]
        else:
            s = s.replace("</head>", tag + "</head>", 1)
    return s


def main(argv):
    check = "--check" in argv
    changed = []
    for path, rel in pages():
        src = open(path, encoding="utf-8").read()
        out = fix(src, rel)
        if out != src:
            changed.append(rel)
            if not check:
                open(path, "w", encoding="utf-8").write(out)
    verb = "would change" if check else "updated"
    for rel in changed:
        print("  %s %s" % (verb, rel))
    print("%d page(s) %s. Light mode on %d page(s)." % (len(changed), verb, sum(1 for _, r in pages() if light_ok(r))))
    return 1 if (check and changed) else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
