#!/usr/bin/env python3
"""
Write the SportsEvent schema on /games from data/fixtures.json.

WHY THIS EXISTS
/games is the second busiest page on the site and the only sports page with
nothing a machine can read. Its entire content is dated, located, entity-rich
events, which is exactly what SportsEvent markup is for, and yet a blog post
about a single game outranked the fixtures hub structurally.

Hand-writing the block was never an option: the fixtures change every time a
new kampe_*.csv lands, and a schedule that disagrees with the page is worse
than no schedule at all. So it is generated from the same fixtures.json the
page itself renders from, and it is regenerated by tools/build-fixtures.py on
every rebuild.

WHAT GETS PUBLISHED
Only games that are worth a machine's attention:
  - still to be played, so an answer engine is never told about a past fixture
  - starting in the future by the clock, not only unplayed, so a game whose
    date has passed without a score typed drops out on the next run
  - state "confirmed", so nothing marked tbc or moving is published as fact
  - carrying both a date+time and a venue
  - at a venue with a street address on record (VENUE_ADDRESS). Google
    requires location.address on every Event, and away halls have none on
    record, so away games stay on the page and off the schema (23 Sep 2026).
  - a Talata home game (g["home"]). Talata is named as organizer, so an away
    game is never published, even one another club hosts at one of the halls
    above. The venue check alone does not guarantee that.

Each event's url is /games#g-<fixture id>. /games opens that game's detail
panel from the hash (talata-fixtures.js, openFromHash), so the url lands on the
game itself rather than the top of the schedule.

Because past games drop off by the clock, --check reports "would update" after
every game day. tools/ship.py regenerates the block when run without --check.

Home games say isAccessibleForFree, because every Talata home game is free to
watch.

    python3 tools/apply-games-schema.py            # apply
    python3 tools/apply-games-schema.py --check    # report, change nothing
"""

import json
import sys
from datetime import datetime, timedelta
from pathlib import Path
from urllib.parse import quote
from zoneinfo import ZoneInfo

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://talatabasketball.dk"
TZ = ZoneInfo("Europe/Copenhagen")
# A league game runs about two hours door to door. Google wants an endDate.
GAME_LENGTH = timedelta(hours=2)
# games.html's own og:image.
IMAGE = SITE + "/images/og/talata-huddle-og.jpg"

START = "<!-- TALATA:GAMESLD:START — generated by tools/apply-games-schema.py, do not hand-edit -->"
END = "<!-- TALATA:GAMESLD:END -->"

# Addresses are only published for venues whose address is recorded somewhere
# we control. A game anywhere else is left out of the schema: a wrong address
# in structured data sends a family to the wrong building, guessing one from a
# hall name is exactly how that happens, and Google rejects an Event with no
# address at all. Add a postalCode to Nørre Fælled Skole only once programs.md
# records it.
#   Svanemøllehallen  — programs.md line 46
#   Nørre Fælled Skole — programs.md line 160, recorded 8 Sep 2026
VENUE_ADDRESS = {
    "Svanemøllehallen": {
        "streetAddress": "Østerbrogade 240",
        "addressLocality": "København Ø",
        "postalCode": "2100",
        "addressCountry": "DK",
    },
    "Nørre Fælled Skole": {
        "streetAddress": "Biskop Krags Vænge 7",
        "addressLocality": "København",
        "addressCountry": "DK",
    },
}


def start_of(g):
    s = datetime.strptime("%s %s" % (g["date"], g["time"]), "%Y-%m-%d %H:%M")
    # Copenhagen, so the offset is +02:00 in summer and +01:00 after the October
    # switch. Let the zone decide rather than hardcoding either one.
    return s.replace(tzinfo=TZ)


def publishable(g):
    return bool(
        not g.get("played")
        # An annulled game is never a scheduled event, even before a score is
        # typed (15 Sep 2026, same rule the page applies in talata-fixtures.js).
        and not g.get("annulled")
        and g.get("state") == "confirmed"
        and g.get("date")
        and g.get("time")
        and g.get("venue")
        # Google needs a street address on every Event and away halls have
        # none on record. Away games stay on the page and off the schema.
        and g["venue"] in VENUE_ADDRESS
        # Talata is the organizer on every published event, so only home
        # games qualify. An away game at one of our halls is the host's event.
        and g.get("home")
        # A game that has started is never an upcoming event, score or not.
        and start_of(g) > datetime.now(TZ)
    )


def event(g):
    """One SportsEvent. Talata is always one of the two sides."""
    start = start_of(g)
    # The page opens this game's detail panel from #g-<id>.
    url = "%s/games#g-%s" % (SITE, quote(str(g["id"]), safe=""))

    us = "Talata %s" % g["team"]
    them = g["opponent"]
    home, away = (us, them) if g.get("home") else (them, us)

    place = {
        "@type": "Place",
        "name": g["venue"],
        "address": dict({"@type": "PostalAddress"}, **VENUE_ADDRESS[g["venue"]]),
    }

    ev = {
        "@context": "https://schema.org",
        "@type": "SportsEvent",
        "name": "%s vs %s" % (home, away),
        "description": "%s, %s." % (g["competition"], g["venue"]),
        "sport": "Basketball",
        "startDate": start.isoformat(),
        "endDate": (start + GAME_LENGTH).isoformat(),
        "eventStatus": "https://schema.org/EventScheduled",
        "eventAttendanceMode": "https://schema.org/OfflineEventAttendanceMode",
        "location": place,
        "image": IMAGE,
        "homeTeam": {"@type": "SportsTeam", "name": home},
        "awayTeam": {"@type": "SportsTeam", "name": away},
        "performer": [
            {"@type": "SportsTeam", "name": home},
            {"@type": "SportsTeam", "name": away},
        ],
        "organizer": {
            "@type": "SportsOrganization",
            "name": "Talata Basketball",
            "url": SITE,
        },
        "url": url,
    }
    if g.get("home"):
        # Every Talata home game is free to watch. publishable() only lets
        # home games through, but the guard stays: an away game is the other
        # club's gate, so we say nothing about it.
        ev["isAccessibleForFree"] = True
        ev["offers"] = {
            "@type": "Offer",
            "price": "0",
            "priceCurrency": "DKK",
            "availability": "https://schema.org/InStock",
            "url": url,
        }
    return ev


def render(games):
    picks = sorted([g for g in games if publishable(g)], key=lambda g: (g["date"], g["time"]))
    if not picks:
        return "", 0
    body = ",\n".join(
        json.dumps(event(g), ensure_ascii=False, indent=2) for g in picks
    )
    return '<script type="application/ld+json">\n[\n%s\n]\n</script>' % body, len(picks)


def main():
    check = "--check" in sys.argv
    games = json.loads((ROOT / "data" / "fixtures.json").read_text(encoding="utf-8"))["games"]
    block, n = render(games)

    page = ROOT / "games.html"
    src = page.read_text(encoding="utf-8")
    if START not in src or END not in src:
        print("games.html is missing the TALATA:GAMESLD markers, nothing to fill")
        return 1

    head, rest = src.split(START, 1)
    _, tail = rest.split(END, 1)
    new = head + START + "\n" + block + "\n" + END + tail

    if new == src:
        print("games schema  no change  (%d upcoming games)" % n)
        return 0
    if check:
        print("games schema  would update  (%d upcoming games)" % n)
        return 0
    page.write_text(new, encoding="utf-8")
    print("games schema  updated  (%d upcoming games)" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
