#!/usr/bin/env python3
"""
Write the Product schema on /shop from the catalogue in assets/talata-shop.js.

WHY THIS EXISTS
/shop had no structured data at all, and the grid is built client-side, so a
crawler saw an empty <div> where fifteen products should be. Grepping the page
for "Heavy hoodie" or "Sweatpants" returned nothing.

WHY IT IS GENERATED AND NOT TYPED
Because the money must not be written down twice. This file already has that
scar: the bundle comment block drifted off the live array on three of five rows
and had to be corrected on 14 Aug 2026. The prices are parsed out of
talata-shop.js, which is checked against the table in
SecondBrain/Talata/programs.md, and programs.md wins if they ever disagree.

TWO THINGS THIS DELIBERATELY DOES NOT DO
  - It publishes ONE offer, at the public price. The member price is a club
    rate, not something a stranger can buy, and two bare Offers on one Product
    is a price mismatch a crawler resolves by picking whichever it likes.
  - It never says InStock. talata-shop.js is explicit that 'in' is a promise
    that only holds when every size in the dropdown could be filled today, and
    right now nothing carries it: the catalogue is 'made' or 'soon' throughout.
    Both map to PreOrder. READY_NOW is left out entirely: those are single loose
    pieces, claimed by email, fetched at runtime.

    python3 tools/apply-shop-schema.py            # apply
    python3 tools/apply-shop-schema.py --check    # report, change nothing
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://talatabasketball.dk"

START = "<!-- TALATA:SHOPLD:START — generated by tools/apply-shop-schema.py, do not hand-edit -->"
END = "<!-- TALATA:SHOPLD:END -->"

# 'made' = made to order, 'soon' = ordered and on its way. Neither is stock on a
# shelf, so neither is InStock.
AVAILABILITY = {
    "made": "https://schema.org/PreOrder",
    "soon": "https://schema.org/PreOrder",
    "in": "https://schema.org/InStock",
}

FIELD = re.compile(
    r"id:\s*'(?P<id>[\w_]+)'.*?"
    r"name:\s*'(?P<name>[^']+)'.*?"
    r"member:\s*(?P<member>\d+).*?"
    r"pub:\s*(?P<pub>\d+).*?"
    r"stock:\s*'(?P<stock>\w+)'",
    re.S,
)


def parse_array(src: str, var: str):
    """Pull one object-literal array out of the shop script."""
    m = re.search(r"var %s = \[(.*?)\n  \];" % var, src, re.S)
    if not m:
        raise SystemExit("could not find %s in assets/talata-shop.js" % var)
    out = []
    for line in m.group(1).split("\n"):
        line = line.strip()
        if not line.startswith("{"):
            continue  # comment lines between entries
        f = FIELD.search(line)
        if not f:
            raise SystemExit("unparsed catalogue row: %s" % line[:70])
        d = f.groupdict()
        d["member"], d["pub"] = int(d["member"]), int(d["pub"])
        desc = re.search(r"desc:\s*'([^']*)'", line)
        d["desc"] = desc.group(1) if desc else ""
        out.append(d)
    return out


def product(p):
    d = {
        "@type": "Product",
        "name": p["name"],
        "sku": p["id"],
        "brand": {"@type": "Brand", "name": "Talata Basketball"},
        "category": "Sportswear",
        "url": "%s/shop" % SITE,
        "offers": {
            "@type": "Offer",
            "price": str(p["pub"]),
            "priceCurrency": "DKK",
            "availability": AVAILABILITY[p["stock"]],
            "url": "%s/shop" % SITE,
            "seller": {"@type": "Organization", "name": "Talata Basketball"},
        },
    }
    if p["desc"]:
        d["description"] = p["desc"]
    return d


def render(items):
    graph = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "Talata Basketball shop",
        "numberOfItems": len(items),
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "item": product(p)}
            for i, p in enumerate(items)
        ],
    }
    return '<script type="application/ld+json">\n%s\n</script>' % json.dumps(
        graph, ensure_ascii=False, indent=2
    )


def main():
    check = "--check" in sys.argv
    js = (ROOT / "assets" / "talata-shop.js").read_text(encoding="utf-8")
    items = parse_array(js, "CATALOGUE") + parse_array(js, "BUNDLES")

    bad = [p for p in items if p["stock"] not in AVAILABILITY]
    if bad:
        raise SystemExit("unknown stock state: %s" % ", ".join(p["id"] for p in bad))

    page = ROOT / "shop.html"
    src = page.read_text(encoding="utf-8")
    if START not in src or END not in src:
        print("shop.html is missing the TALATA:SHOPLD markers, nothing to fill")
        return 1

    head, rest = src.split(START, 1)
    _, tail = rest.split(END, 1)
    new = head + START + "\n" + render(items) + "\n" + END + tail

    instock = sum(1 for p in items if p["stock"] == "in")
    note = "  (%d products, %d in stock)" % (len(items), instock)
    if new == src:
        print("shop schema   no change" + note)
        return 0
    if check:
        print("shop schema   would update" + note)
        return 0
    page.write_text(new, encoding="utf-8")
    print("shop schema   updated" + note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
