#!/usr/bin/env python3
"""
Swap the shared Talata footer into every page.

The sibling of tools/apply-shared-header.py, written 20 Aug 2026 for the same
reason and it is worth writing down. An audit that morning found SIX different
footers across the site and, worse, twenty-plus pages with no <footer> element
at all:

    academy · mini · sparks · join · camps · pathway · coaches
    school-partnerships · ish-high-school · ish-primary-school
    basketball-in-copenhagen · every page under camps/ · two blog posts

Those are the pages Google actually lands people on. A parent who searched
"basketball club copenhagen kids", read /academy top to bottom and decided yes
hit the end of the page with no email address, no WhatsApp link, no trial CTA
and no way back into the site. /shop had a literal empty `<footer
id="drawer-foot"></footer>`.

The footer is also where everything cut from the nav has to land, so the nav can
shrink without orphaning a page. Keep that contract: if you remove an item from
MENU in apply-shared-header.py, it must appear in COLUMNS here.

Idempotent. Re-running replaces the injected block rather than stacking copies,
so this is the way to roll a footer change across the site.

    python3 tools/apply-shared-footer.py            # apply
    python3 tools/apply-shared-footer.py --check    # report, change nothing
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Same skip list as the header tool: dead prototypes and print-only pages.
SKIP = {
    "index-new.html",
    "home-classic.html",
    "hero-carousel-preview.html",
    "posters/spring-camp-u13-u15-poster.html",
    "posters/spring-camp-u9-u11-poster.html",
}

START = "<!-- TALATA:FOOTER:START — generated by tools/apply-shared-footer.py, do not hand-edit -->"
END = "<!-- TALATA:FOOTER:END -->"

# One line, not the old three. The homepage footer used to carry a 45-word
# paragraph that ended up 16 lines tall and 14 characters wide on a phone.
# The philosophy sentence it lost has its own page, linked below.
BLURB = "Copenhagen's basketball club. Camps since 2021, competitive teams since 2024."

ADDRESS = (
    "Svanem&oslash;llehallen, &Oslash;sterbro &middot; "
    "Strandvejsskolen, Sionsgade 1, 2100 K&oslash;benhavn &Oslash;"
)

# CVR belongs in a footer for a Danish forening. It was dropped from the site on
# 6 Aug 2026 because it was sitting in the header where it read as clutter. The
# footer is where a company number is supposed to live.
CVR = "CVR 43599453"

# Every destination the nav does not have room for lives here. Nothing on this
# site should be reachable only from the nav.
# Cut to four short columns on 26 Aug 2026, following zalgiris.lt/en (Deng).
# It was a 22-link sitemap in three columns, which is a site map rather than a
# footer: everything present, nothing findable. A footer answers "where do I go
# next", and the nav already carries the full structure.
#
# Talata's columns are NOT Zalgiris's. They have Tickets because they sell them
# and a Men/Women/Kids shop split because they have one. Entry to a Talata game
# is free and the shop is one page, so those become Play and Watch: the two
# things a visitor is actually here to do.
COLUMNS = [
    ("Play", [
        ("/mini", "Mini + Junior"),
        ("/academy", "Academy"),
        ("/sparks", "Sparks"),
        ("/men", "Talata Men"),
        ("/camps", "Camps"),
    ]),
    ("Watch", [
        ("/games", "Games"),
        ("/games#season", "Fixtures"),
        ("/gallery", "Gallery"),
        ("/blog", "The Playbook"),
    ]),
    ("Club", [
        ("/coaches", "Coaches"),
        ("/pathway", "Player Pathway"),
        ("/help/age-groups", "Prices and times"),
        ("/help", "Help &amp; guides"),
        ("/partners", "Partners"),
    ]),
    ("Shop", [
        ("/shop", "Gear"),
        ("/shop#bundles", "Bundles"),
        ("/shop#jerseys", "Game jerseys"),
    ]),
]

# Deng's phone number is deliberately NOT here (removed 20 Aug 2026, his call).
# The footer went on all 46 pages, so a tel: link there published his personal
# mobile 46 times over. Email is the contact of record; WhatsApp stays because it
# is a channel labelled by name, not a number on display.
CONTACT = [
    ("mailto:coach@talatabasketball.dk", "coach@talatabasketball.dk"),
    ("https://wa.me/4552398508", "WhatsApp Coach Deng"),
]

SOCIAL = [
    ("https://www.instagram.com/talatabasketball/", "Instagram"),
    ("https://www.facebook.com/talatabasketball", "Facebook"),
]

CSS_TAG = '<link rel="stylesheet" href="/assets/talata-footer.css?v=20260903a">'

# Per page trial CTA, mirroring apply-shared-header.py's CTA map. A footer that
# says "Book a free trial" must land on that page's own form, not scroll-to-top
# on a page with no form.
TRIAL = {
    "index.html": "#trial",
    "academy.html": "#apply",
    "mini.html": "#register",
    "sparks.html": "#register",
    "join.html": "#register",
    "ish-primary-school.html": "#signup",
    "ish-high-school.html": "#signup",
    "school-partnerships.html": "#contact",
    "camps/autumn-camp-2026.html": "#waitlist",
    "camps/winter-camp-2026.html": "#waitlist",
    "camps/lithuania-camp-2026.html": "#register",
}
DEFAULT_TRIAL = "/join"


def build_footer(rel: str, year: int = 2026) -> str:
    """Render the footer markup for one page."""
    trial = TRIAL.get(rel, DEFAULT_TRIAL)

    cols = []
    for title, items in COLUMNS:
        links = "".join(
            '\n        <a href="%s">%s</a>' % (href, label) for href, label in items
        )
        cols.append(
            '      <div class="tf-col">\n        <h4>%s</h4>%s\n      </div>'
            % (title, links)
        )

    contact = "".join(
        '\n        <a href="%s">%s</a>' % (href, label) for href, label in CONTACT
    )
    contact += '\n        <a href="%s"><b>Book a free trial &rarr;</b></a>' % trial
    cols.append(
        '      <div class="tf-col">\n        <h4>Contact</h4>%s\n      </div>' % contact
    )

    social = "".join(
        '<a href="%s" target="_blank" rel="noopener">%s</a>' % (href, label)
        for href, label in SOCIAL
    )

    return """{start}
<footer class="tf">
  <div class="tf-wrap">
    <div class="tf-grid">
      <div class="tf-id">
        <h4>Talata Basketball</h4>
        <p>{blurb}</p>
        <p class="tf-meta">{address}<br>{cvr}</p>
        <div class="tf-social">{social}</div>
      </div>
{cols}
    </div>
    <div class="tf-base">
      <span>&copy; {year} Talata Basketball &middot; Copenhagen &Oslash;</span>
      <span>First session is always free. You need indoor shoes, nothing else.</span>
    </div>
  </div>
</footer>
{end}""".format(
        start=START,
        end=END,
        blurb=BLURB,
        address=ADDRESS,
        cvr=CVR,
        social=social,
        cols="\n".join(cols),
        year=year,
    )


INJECTED = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)
FOOTER_OPEN = re.compile(r"<footer\b([^>]*)>", re.I)

# A <footer> tag is not proof of a page footer, and getting this wrong is
# expensive. Two live examples on this site:
#
#   shop.html      <footer id="drawer-foot"></footer>  is the BASKET drawer.
#                  renderCart() writes the MobilePay checkout steps into it by
#                  id. Replacing it silently breaks paying for merch.
#   philosophy/    <footer> inside a <blockquote> is the citation on a quote.
#   reviews/       13 <footer> elements, one per review card, each a byline.
#
# So: never touch a footer that carries an id (an id means JS talks to it), and
# never touch one nested inside a quote, card or list item.
CARD_CONTAINERS = ("article", "blockquote", "figure", "aside", "li", "td", "dialog", "details")


def _element_span(src, start, tag="footer"):
    """End offset of the <tag> element opening at `start`, or None."""
    step = re.compile(r"<(/?)%s\b[^>]*>" % tag, re.I)
    depth = 0
    for t in step.finditer(src, start):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            return t.end()
    return None


def _is_page_level(src: str, start: int, attrs: str) -> bool:
    if re.search(r"\bid\s*=", attrs, re.I):
        return False
    before = src[:start]
    for tag in CARD_CONTAINERS:
        # \b matters. A plain substring count of "<li" also counts every <link>
        # tag in <head>, which left every page thinking it was inside an
        # unclosed list item and stripped nothing at all.
        opens = len(re.findall(r"<%s\b" % tag, before, re.I))
        closes = len(re.findall(r"</%s\b" % tag, before, re.I))
        if opens > closes:
            return False
    return True


# Half the site never used a <footer> element at all. The landing pages and the
# camp pages close with <div class="footer">, styled by each page's own CSS. The
# first roll-out only stripped <footer>, so those 17 pages ended up rendering the
# old div footer AND the new shared one, stacked. Both shapes have to go.
DIV_FOOTER_OPEN = re.compile(r'<div\s+class="footer"([^>]*)>', re.I)


def _next_old_footer(src: str, pos: int):
    """Whichever old-footer shape comes first from `pos`: (match, tag) or None."""
    a = FOOTER_OPEN.search(src, pos)
    b = DIV_FOOTER_OPEN.search(src, pos)
    if a and b:
        return (a, "footer") if a.start() < b.start() else (b, "div")
    if a:
        return a, "footer"
    if b:
        return b, "div"
    return None


def strip_page_footers(src: str) -> tuple[str, int]:
    """Remove page-level footers of both shapes, leaving card and drawer footers alone."""
    removed = 0
    pos = 0
    while True:
        found = _next_old_footer(src, pos)
        if not found:
            break
        m, tag = found
        end = _element_span(src, m.start(), tag)
        if end is None:
            break
        if not _is_page_level(src, m.start(), m.group(1)):
            pos = end
            continue
        # take surrounding whitespace with it so we don't leave a hole
        cut_start = m.start()
        while cut_start > 0 and src[cut_start - 1] in " \t":
            cut_start -= 1
        cut_end = end
        while cut_end < len(src) and src[cut_end] in " \t\r\n":
            cut_end += 1
        src = src[:cut_start] + src[cut_end:]
        removed += 1
        pos = cut_start
    return src, removed


def process(path: Path, check: bool):
    rel = path.relative_to(ROOT).as_posix()
    src = original = path.read_text(encoding="utf-8")
    notes = []

    footer = build_footer(rel)

    # Strip old footers on EVERY run, not just first injection. The first
    # roll-out only knew about <footer>, so 17 pages kept their
    # <div class="footer"> and rendered two footers stacked. Because those pages
    # already carried the markers, a re-run took the "refreshed" branch and could
    # never clean them up. Strip first, then place, always.
    injected = INJECTED.search(src)
    if injected:
        # protect the generated block from its own stripper
        src = INJECTED.sub("\x00FOOTER\x00", src, count=1)

    src, removed = strip_page_footers(src)
    if removed:
        notes.append("removed %d old footer(s)" % removed)

    if injected:
        src = src.replace("\x00FOOTER\x00", footer, 1)
        notes.append("refreshed")
    else:
        body_end = src.rfind("</body>")
        if body_end == -1:
            return rel, ["NO </body> — skipped"], False
        src = src[:body_end] + footer + "\n\n" + src[body_end:]
        notes.append("injected")

    if "/assets/talata-footer.css?v=20260903a" not in src:
        head = src.find("</head>")
        if head != -1:
            src = src[:head] + CSS_TAG + "\n" + src[head:]
            notes.append("css tag")

    changed = src != original
    if changed and not check:
        path.write_text(src, encoding="utf-8")
    return rel, notes, changed


def main():
    check = "--check" in sys.argv
    pages = sorted(
        p for p in ROOT.glob("**/*.html")
        if "node_modules" not in p.parts
        and ".wrangler" not in p.parts
        and p.relative_to(ROOT).as_posix() not in SKIP
    )
    touched = 0
    for page in pages:
        rel, notes, changed = process(page, check)
        if changed:
            touched += 1
        print("%-52s %s" % (rel, ", ".join(notes) if changed else "no change"))
    print("\n%d page(s) %s of %d" % (touched, "would change" if check else "updated", len(pages)))


if __name__ == "__main__":
    main()
