#!/usr/bin/env python3
"""
Write the ItemList schema on /shop from the catalogue in assets/talata-shop.js.

WHY THIS EXISTS
/shop had no structured data at all, and the grid is built client-side, so a
crawler saw an empty <div> where fifteen products should be. Grepping the page
for "Heavy hoodie" or "Sweatpants" returned nothing.

WHY IT IS NAMES ONLY (23 Sep 2026)
Until 23 Sep each ListItem carried a full Product with an Offer. Search Console
flagged every one under Merchant listings and Product snippets, and it always
will: all fifteen items sit on one URL (/shop), and the page has no product
photos by design. Google only grants a product rich result to a Product with an
image, ideally on its own page, so that markup could never earn anything and
only produced warnings. Each ListItem now carries the item's name and nothing
else. No Product, no Offer, no price, so nothing here can drift from the money.
If the shop ever gets one page per item with a photo, Product markup goes on
that page, not here.

WHY IT IS GENERATED AND NOT TYPED
The names are parsed out of talata-shop.js, the one catalogue the page renders
from, so a renamed or added item shows up here on the next run. Prices stay in
talata-shop.js, checked against SecondBrain/Talata/programs.md, which wins if
they ever disagree. READY_NOW is left out: those are single loose pieces,
claimed by email, fetched at runtime.

    python3 tools/apply-shop-schema.py            # apply
    python3 tools/apply-shop-schema.py --check    # report, change nothing
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = "https://talatabasketball.dk"

START = "<!-- TALATA:SHOPLD:START — generated by tools/apply-shop-schema.py, do not hand-edit -->"
END = "<!-- TALATA:SHOPLD:END -->"

FIELD = re.compile(
    r"id:\s*'(?P<id>[\w_]+)'.*?"
    r"name:\s*'(?P<name>[^']+)'.*?"
    r"member:\s*(?P<member>\d+).*?"
    r"pub:\s*(?P<pub>\d+).*?"
    r"stock:\s*'(?P<stock>\w+)'",
    re.S,
)


def parse_array(src: str, var: str):
    """Pull one object-literal array out of the shop script."""
    m = re.search(r"var %s = \[(.*?)\n  \];" % var, src, re.S)
    if not m:
        raise SystemExit("could not find %s in assets/talata-shop.js" % var)
    out = []
    for line in m.group(1).split("\n"):
        line = line.strip()
        if not line.startswith("{"):
            continue  # comment lines between entries
        f = FIELD.search(line)
        if not f:
            raise SystemExit("unparsed catalogue row: %s" % line[:70])
        d = f.groupdict()
        d["member"], d["pub"] = int(d["member"]), int(d["pub"])
        out.append(d)
    return out


def render(items):
    graph = {
        "@context": "https://schema.org",
        "@type": "ItemList",
        "name": "Talata Basketball shop",
        "numberOfItems": len(items),
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": p["name"]}
            for i, p in enumerate(items)
        ],
    }
    return '<script type="application/ld+json">\n%s\n</script>' % json.dumps(
        graph, ensure_ascii=False, indent=2
    )


def main():
    check = "--check" in sys.argv
    js = (ROOT / "assets" / "talata-shop.js").read_text(encoding="utf-8")
    items = parse_array(js, "CATALOGUE") + parse_array(js, "BUNDLES")

    page = ROOT / "shop.html"
    src = page.read_text(encoding="utf-8")
    if START not in src or END not in src:
        print("shop.html is missing the TALATA:SHOPLD markers, nothing to fill")
        return 1

    head, rest = src.split(START, 1)
    _, tail = rest.split(END, 1)
    new = head + START + "\n" + render(items) + "\n" + END + tail

    note = "  (%d items, names only)" % len(items)
    if new == src:
        print("shop schema   no change" + note)
        return 0
    if check:
        print("shop schema   would update" + note)
        return 0
    page.write_text(new, encoding="utf-8")
    print("shop schema   updated" + note)
    return 0


if __name__ == "__main__":
    sys.exit(main())
