#!/usr/bin/env python3
"""
Swap the shared Talata header into every page.

Before this existed the site had five different navs and none of them worked on
a phone. This script removes whatever nav a page currently has and injects the
one in assets/talata-nav.{css,js}.

Idempotent: re-running replaces the injected block rather than stacking copies,
so this is the way to roll a nav change (new program, new camp) across the site.

    python3 tools/apply-shared-header.py            # apply
    python3 tools/apply-shared-header.py --check    # report, change nothing
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Dead prototypes and print-only pages. Not served, not worth a nav.
SKIP = {
    "index-new.html",
    "home-classic.html",
    "hero-carousel-preview.html",
    "posters/spring-camp-u13-u15-poster.html",
    "posters/spring-camp-u9-u11-poster.html",
}

# Per page: (cta_href, cta_label). Anchors verified against each page's form id.
CTA = {
    "basketball-in-copenhagen.html": ("/join", "Book free trial"),
    "index.html": ("#trial", "Book free trial"),
    "academy.html": ("#apply", "Book free trial"),
    "mini.html": ("#register", "Book free trial"),
    "sparks.html": ("#register", "Book free trial"),
    "join.html": ("#register", "Book free trial"),
    "ish-primary-school.html": ("#signup", "Sign up"),
    "ish-high-school.html": ("#signup", "Sign up"),
    "school-partnerships.html": ("#contact", "Get in touch"),
    "camps/autumn-camp-2026.html": ("#waitlist", "Join waitlist"),
    "camps/starter-camp-2026.html": ("#waitlist", "Join waitlist"),
    "camps/winter-camp-2026.html": ("#waitlist", "Join waitlist"),
    "camps/lithuania-camp-2026.html": ("#register", "Sign up"),
}
DEFAULT_CTA = ("/#trial", "Book free trial")

# Resolved per page in build_header(): "#watch" on the homepage, "/#watch"
# elsewhere. Watch is an on-page section, not a standalone URL.
WATCH_PLACEHOLDER = "__WATCH__"

# Placement is deliberately NOT in this menu (Deng, 22 Aug): it is a commercial
# service that will sit in its own company, not a club activity. A forening's
# site should not run a commercial funnel with its own tab. /placement stays
# live and indexed, reachable from /pathway and the footer.
# Restructured 22 Aug 2026. Placement went live as a product, and a product
# that sells does not belong four levels deep inside "Club". Pathway becomes its
# own tab; Club absorbs the practical parent pages that used to sit in "Parents".
# Still five tabs, longest dropdown still 6. Gallery and Contact were not
# orphaned: the shared footer carries the full site map on every page.
# Reduced 25 Aug 2026 (Deng: fewer clicks, less friction). 21 dropdown rows to 12.
# The audit found the single worst gap: PRICES were three clicks deep and no nav
# or footer row contained the word price. The fee table at /help/age-groups was
# linked from neither. It is now its own tab.
# Also fixed: five tabs duplicated their own first row, and /join sat in the nav
# twice as "Talata Men" and as "Contact". Mini and Junior were two rows for one page.
# Dropped to the footer, which already carries them: The Talata Way, The Playbook,
# Gallery, Parents' Guide, Help. Canada and the three camp rows are on /camps.
MENU = {
    "Programs": [
        ("/mini", "Mini + Junior", "ages 5 to 12"),
        ("/saturday", "Saturdays", "ages 5 to 12, from autumn"),
        ("/academy", "Academy", "ages 13 to 19"),
        ("/sparks", "Sparks", "girls 6 to 14"),
        ("/join", "Adults", "Men 3. Division + fitness"),
        ("/school-partnerships", "Schools", "ISH and school programmes"),
    ],
    # No dropdown. /camps already lists Starter, Pathway, Winter and the archive,
    # so the old five rows were a copy of the page they pointed at.
    "Camps": [],
    # Added 26 Aug 2026. No dropdown: /games is one page holding the whole
    # season, and a dropdown would just be a copy of the page it points at.
    # Top level because a fixture list is the thing a parent, a player and a
    # rival club all look for, and it had no route in at all before this.
    "Games": [],
    "Prices &amp; Times": [
        ("/help/age-groups", "What it costs", "fees and age groups"),
        ("/help/first-session", "Your first session", "what to bring"),
        ("/help/holdsport", "Holdsport", "signing up, in English"),
    ],
    "Club": [
        ("/coaches", "Coaches", "who is on the floor"),
        ("/pathway", "Player Pathway", "where players go next"),
        ("/reviews", "Reviews", "what parents say"),
    ],
}
TOP_HREF = {"Programs": "#programs", "Camps": "/camps", "Games": "/games",
            "Prices &amp; Times": "/help/age-groups", "Club": "/coaches"}

START = "<!-- TALATA:HEADER:START — generated by tools/apply-shared-header.py, do not hand-edit -->"
END = "<!-- TALATA:HEADER:END -->"

CARET = (
    '<svg class="tn-car" viewBox="0 0 10 6" fill="none" aria-hidden="true">'
    '<path d="M1 1l4 4 4-4" stroke="currentColor" stroke-width="1.8" '
    'stroke-linecap="round" stroke-linejoin="round"/></svg>'
)

# talata-dark.css is deliberately LAST in this block, and this block is
# injected AFTER every page's own inline <style>. That ordering is the whole
# mechanism: a later stylesheet of equal specificity wins, so redefining the
# :root tokens here flips all 50 pages without touching their own CSS.
HEAD_TAGS = """<link rel="stylesheet" href="/assets/talata-nav.css">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="icon" href="/favicon.ico" sizes="32x32">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">
<meta name="theme-color" content="#0B0F17">"""

DARK_TAG = '<link rel="stylesheet" href="/assets/talata-dark.css?v=20260826s">'

SCRIPT_TAG = '<script src="/assets/talata-nav.js" defer></script>'


def build_header(is_home: bool, cta_href: str, cta_label: str) -> str:
    """Render the header markup for one page."""
    programs_href = "#programs" if is_home else "/#programs"
    watch_href = "#watch" if is_home else "/#watch"

    desktop, drawer = [], []
    for title, items in MENU.items():
        top = programs_href if title == "Programs" else TOP_HREF[title]
        items = [
            (watch_href if href == WATCH_PLACEHOLDER else href, label, note)
            for href, label, note in items
        ]
        links = "".join(
            '\n        <a href="%s">%s%s</a>'
            % (href, label, "<small>%s</small>" % note if note else "")
            for href, label, note in items
        )
        if not items:
            desktop.append(
                '      <li><a class="tn-top" href="%s">%s</a></li>' % (top, title)
            )
            drawer.append(
                '        <h3><a href="%s">%s</a></h3>' % (top, title)
            )
            continue
        desktop.append(
            '      <li><a class="tn-top" href="%s">%s%s</a>\n'
            "        <div class=\"tn-drop\">%s\n        </div>\n      </li>"
            % (top, title, CARET, links)
        )
        drawer.append(
            '        <h3>%s</h3>\n        <ul class="tn-drawer-list">%s\n        </ul>'
            % (
                title,
                "".join(
                    '\n          <li><a href="%s">%s%s</a></li>'
                    % (href, label, "<small>%s</small>" % note if note else "")
                    for href, label, note in items
                ),
            )
        )

    return """{start}
<a class="tn-skip" href="#tn-content">Skip to content</a>

<div class="tn-util">
  <div class="tn-util-in">
    <p><b>First session free</b><span class="tn-util-x"> &middot; Home court: Svanem&oslash;llehallen, &Oslash;sterbro</span></p>
    <p class="tn-util-links"><a href="https://www.instagram.com/talatabasketball/" target="_blank" rel="noopener">Instagram</a><span>&middot;</span><a href="mailto:coach@talatabasketball.dk">coach@talatabasketball.dk</a></p>
  </div>
</div>

<div class="tn-bar" id="tn-bar">
  <div class="tn-bar-in">
    <a class="tn-logo" href="/">Talata<span>Basketball</span></a>
    <nav class="tn-menu" aria-label="Main">
      <ul>
{desktop}
        <li><a class="tn-top" href="/shop">Shop</a></li>
      </ul>
    </nav>
    <a class="tn-cta" href="{cta_href}">{cta_label} <span aria-hidden="true">&rarr;</span></a>
    <button class="tn-burger" id="tn-burger" type="button" aria-expanded="false" aria-controls="tn-drawer" aria-label="Open menu"><i></i></button>
  </div>
</div>

<div class="tn-scrim" id="tn-scrim" hidden></div>

<aside class="tn-drawer" id="tn-drawer" aria-label="Menu" hidden>
  <div class="tn-drawer-top">
    <a class="tn-logo" href="/">Talata<span>Basketball</span></a>
    <button class="tn-drawer-close" id="tn-drawer-close" type="button" aria-label="Close menu">&#10005;</button>
  </div>
  <div class="tn-drawer-body">
    <a class="tn-drawer-cta" href="{cta_href}">{cta_label} <span aria-hidden="true">&rarr;</span></a>
{drawer}
    <h3>More</h3>
    <ul class="tn-drawer-list">
      <li><a href="/shop">Shop</a></li>
    </ul>
  </div>
  <div class="tn-drawer-foot">
    <a href="https://wa.me/4552398508" target="_blank" rel="noopener">WhatsApp Coach Deng</a>
    <a href="mailto:coach@talatabasketball.dk">Email</a>
    <a href="https://www.instagram.com/talatabasketball/" target="_blank" rel="noopener">Instagram</a>
  </div>
</aside>

<span id="tn-content" tabindex="-1"></span>
{end}""".format(
        start=START,
        end=END,
        desktop="\n".join(desktop),
        drawer="\n".join(drawer),
        watch=watch_href,
        cta_href=cta_href,
        cta_label=cta_label,
    )


# The five nav variants that existed before this script: the homepage's util bar
# + .menu, .nav-links on the program pages, .site-header on the camps pages,
# logo-only on blog posts, and the Tailwind nav on /philosophy. Matched by their
# opening tag, then closed by counting nested tags — regex alone gets this wrong
# on the util bar, which is three divs deep.
OLD_NAV_OPEN = [
    re.compile(r'<div class="util">'),          # homepage utility bar
    re.compile(r'<header class="site-header">'),  # camps.html + spring camp pages
    re.compile(r"<nav\b[^>]*>"),                # every other variant
]
INJECTED = re.compile(re.escape(START) + r".*?" + re.escape(END), re.S)


def strip_element(src: str, open_re: re.Pattern) -> tuple[str, bool]:
    """Remove the first element matching open_re, closing tags counted properly."""
    m = open_re.search(src)
    if not m:
        return src, False
    tag = re.match(r"<(\w+)", m.group(0)).group(1)
    step = re.compile(r"<(/?)%s\b[^>]*>" % tag, re.I)
    depth, pos = 0, m.start()
    for t in step.finditer(src, m.start()):
        depth += -1 if t.group(1) else 1
        if depth == 0:
            end = t.end()
            # take the trailing newline with it so we don't leave blank gaps
            while end < len(src) and src[end] in " \t":
                end += 1
            if end < len(src) and src[end] == "\n":
                end += 1
            # and any indentation left on the opening line
            while pos > 0 and src[pos - 1] in " \t":
                pos -= 1
            return src[:pos] + src[end:], True
    return src, False


def process(path: Path, check: bool):
    rel = path.relative_to(ROOT).as_posix()
    src = original = path.read_text(encoding="utf-8")
    notes = []

    is_home = rel == "index.html"
    cta_href, cta_label = CTA.get(rel, DEFAULT_CTA)
    header = build_header(is_home, cta_href, cta_label)

    if INJECTED.search(src):
        src = INJECTED.sub(lambda _: header, src, count=1)
        notes.append("refreshed")
    else:
        for pattern in OLD_NAV_OPEN:
            src, removed = strip_element(src, pattern)
            if removed:
                notes.append("removed old nav")
        body = re.search(r"<body[^>]*>", src)
        if not body:
            return rel, ["NO <body> — skipped"], False
        src = src[: body.end()] + "\n\n" + header + "\n" + src[body.end():]
        notes.append("injected")

    if "/assets/talata-nav.css" not in src:
        head = re.search(r"</head>", src)
        if head:
            src = src[: head.start()] + HEAD_TAGS + "\n" + src[head.start():]
            notes.append("head tags")
    # Dark mode, 26 Aug 2026. Re-stamped on EVERY run, not just a page's first,
    # and always immediately before </head> so it stays the last stylesheet on
    # the page. That position is what lets it redefine the :root tokens each
    # page sets in its own inline <style>. Removing any previous copy first is
    # what makes a ?v= bump actually reach the pages.
    src = re.sub(r'[ \t]*<link rel="stylesheet" href="/assets/talata-dark\.css[^"]*">\n?', "", src)
    head = re.search(r"</head>", src)
    if head:
        src = src[: head.start()] + DARK_TAG + "\n" + src[head.start():]
        notes.append("dark css")

    if "/assets/talata-nav.js" not in src:
        body_end = src.rfind("</body>")
        if body_end != -1:
            src = src[:body_end] + SCRIPT_TAG + "\n" + src[body_end:]
            notes.append("script tag")

    changed = src != original
    if changed and not check:
        path.write_text(src, encoding="utf-8")
    return rel, notes, changed


def main():
    check = "--check" in sys.argv
    pages = sorted(
        p for p in ROOT.glob("**/*.html")
        if "node_modules" not in p.parts
        and ".wrangler" not in p.parts
        and p.relative_to(ROOT).as_posix() not in SKIP
    )
    touched = 0
    for page in pages:
        rel, notes, changed = process(page, check)
        if changed:
            touched += 1
        print("%-52s %s" % (rel, ", ".join(notes) if changed else "no change"))
    print("\n%d page(s) %s of %d" % (touched, "would change" if check else "updated", len(pages)))


if __name__ == "__main__":
    main()
