#!/usr/bin/env python3
"""
Rebuild the placement page's network panel from tools/network.json.

Keeps the claim tiers honest: "placed" entries name the player and the year,
"known" entries make no claim beyond that we know them. Leagues render as
logos where we have a file and as text where we do not, so a missing logo
degrades instead of leaving a hole.

    python3 tools/build-network-panel.py
"""
import json, html
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = json.loads((ROOT / "tools" / "network.json").read_text(encoding="utf-8"))
PAGE = ROOT / "placement.html"
START = "  <!-- TALATA:NETWORK:START generated by tools/build-network-panel.py -->"
END = "  <!-- TALATA:NETWORK:END -->"

def esc(t): return html.escape(t, quote=False)

def card(e, placed=False):
    cls = ' class="placed"' if placed else ""
    out = ["      <div%s>" % cls, '        <div class="n">%s</div>' % esc(e["name"])]
    if e.get("where"):
        out.append('        <div class="l">%s</div>' % esc(e["where"]))
    if placed and e.get("who"):
        out.append('        <div class="who">%s</div>' % esc(e["who"]))
    out.append("      </div>")
    return "\n".join(out)

def league(l):
    logo = l.get("file", "")
    if logo and (ROOT / "images" / "leagues" / logo).exists():
        inner = '<img src="/images/leagues/%s" alt="%s" loading="lazy">' % (esc(logo), esc(l["name"]))
    else:
        inner = '<span class="lg-text">%s</span>' % esc(l.get("short") or l["name"])
    if l.get("url"):
        return ('    <a class="lg" href="%s" target="_blank" rel="noopener" aria-label="%s">%s</a>'
                % (esc(l["url"]), esc(l["name"]), inner))
    return '    <div class="lg" aria-label="%s">%s</div>' % (esc(l["name"]), inner)

groups = DATA.get("groups", [])
placed = DATA.get("placed", [])
leagues = DATA.get("leagues", [])

parts = ['  <div class="band">', '  <section class="section section-wide">',
         '    <div class="kicker">The network</div>',
         '    <h2 class="section-title">%s</h2>' % esc(DATA["heading"]),
         "    <p>%s</p>" % esc(DATA["intro"]), '    <div class="tiers">']

if placed:
    parts.append('      <div class="tier-lbl">Players placed here</div>')
    parts.append('      <div class="dest">')
    parts += [card(e, True) for e in placed]
    parts.append("      </div>")

for g in groups:
    parts.append('      <div class="tier-lbl">%s</div>' % esc(g["label"]))
    parts.append('      <div class="dest">')
    parts += [card(e) for e in g["entries"]]
    parts.append("      </div>")
parts.append("    </div>")

if leagues:
    parts.append('    <div class="tier-lbl" style="margin-top:30px">Leagues our network competes in</div>')
    parts.append('    <div class="leagues">')
    parts += [league(l) for l in leagues]
    parts.append("    </div>")

if DATA.get("note"):
    parts.append('    <p class="note">%s</p>' % DATA["note"])
parts += ["  </section>", "  </div>", ""]

page = PAGE.read_text(encoding="utf-8")
i, j = page.index(START), page.index(END)
PAGE.write_text(page[:i] + START + "\n" + "\n".join(parts) + END + page[j + len(END):], encoding="utf-8")
n_progs = sum(len(g["entries"]) for g in groups)
print("panel rebuilt: %d placed, %d programmes, %d leagues" % (len(placed), n_progs, len(leagues)))
